version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 25
  reviewers:
  - mprins
  assignees:
  - mprins
  labels:
  - dependencies
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  assignees:
  - mprins
  labels:
  - build infrastructure
